#!/usr/bin/env bash

#SBATCH -o /homes/8/cpb28/slurm_log/deepsurfer-train-%j.out
#SBATCH -J deepsurfer-train-train
#SBATCH -p rtx8000
#SBATCH -A qtim
#SBATCH -n 1
#SBATCH --cpus-per-task=3
#SBATCH --gres=gpu:1
#SBATCH -t 4:00:00
#SBATCH --mem=40G

export PYENV_VERSION="deepsurfer-train"
python -m deepsurfer_train train \
    default_data_config.json \
    unet_model_config.json \
    /autofs/cluster/qtim/projects/deepsurfer/checkpoints/basic_unet
